run-name: Ubuntu22.04 - ${{ (github.event.pull_request.title || 'scheduled/manual run') }}
on:
  workflow_dispatch:
    inputs:
      CUSTOM_REPOSITORY:
        description: 'Custom repository (owner/repo)'
        required: false
      CUSTOM_REPOSITORY_COMMIT_HASH:
        description: 'Commit hash'
        required: false
  pull_request_target:
    types: labeled
    paths:
    - 'images/linux/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Ubuntu_2204:
    if: ${{ (github.event.label.name == 'ubuntu-all') || (github.event.label.name == 'ubuntu-2204') || (inputs.CUSTOM_REPOSITORY != '' && inputs.CUSTOM_REPOSITORY_COMMIT_HASH != '') || (github.event_name == 'schedule') }}
    uses: ./.github/workflows/ubuntu-win-generation.yml
    with:
      image_name: 'ubuntu2204'
      image_readme_name: 'Ubuntu2204-Readme.md'
      custom_repo: ${{ github.event.inputs.CUSTOM_REPOSITORY }}
      custom_repo_commit_hash: ${{ github.event.inputs.CUSTOM_REPOSITORY_COMMIT_HASH }}
    secrets: inherit
