run-name: Windows 2022 - ${{ (github.event.pull_request.title || 'scheduled/manual run') }}
on:
  workflow_dispatch:
    inputs:
      CUSTOM_REPOSITORY:
        description: 'Custom repository (owner/repo)'
        required: false
      CUSTOM_REPOSITORY_COMMIT_HASH:
        description: 'Commit hash'
        required: false
  pull_request_target:
    types: labeled
    paths:
    - 'images/win/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Windows_2022:
    if: ${{ (github.event.label.name == 'CI windows-all') || (github.event.label.name == 'CI windows-2022') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule') }}
    uses: ./.github/workflows/ubuntu-win-generation.yml
    with:
      image_name: 'windows2022'
      image_readme_name: 'Windows2022-Readme.md'
      custom_repo: ${{ github.event.inputs.CUSTOM_REPOSITORY }}
      custom_repo_commit_hash: ${{ github.event.inputs.CUSTOM_REPOSITORY_COMMIT_HASH }}
    secrets: inherit
